import { render, screen } from '@testing-library/react';
import App from './App';

//This was autogenerated when I ran the About JS run
test('renders learn react link', () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});
